version: "3.1"
services:
    www:
        container_name: pdvb_apache
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        container_name: pdvb_bd
        image: mysql:8.0
        ports: 
            - "3307:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: pdvb
            MYSQL_USER: pdvb
            MYSQL_PASSWORD: pdvbpassw
            MYSQL_ROOT_PASSWORD: pdvbpassw 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        container_name: pdvb_phpmyadmin
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: pdvb
            MYSQL_PASSWORD: pdvbpassw
            MYSQL_ROOT_PASSWORD: pdvbpassw 
volumes:
    persistent:
